title: "woody work"
description: "وبسایت یه آچارفرانسه"
baseurl: "https://woodywork.ir/" # آدرس زیردامنه
url: "https://iweiu1005.github.io" # آدرس کامل سایت

# تنظیمات نویسنده
author:
  name: "woody"

# تم سایت (از تم‌های پیش‌فرض گیت‌هاب)
theme: jekyll-theme-minimal

# پلاگین‌ها
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# تنظیمات مارک‌داون
markdown: kramdown
highlighter: rouge

# تنظیمات دیگر
permalink: /:year/:month/:day/:title/
timezone: Asia/Tehran
